name: Trigger deployment of application on Linux depending on environment
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - test
jobs:
  runOnAnsible:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      
    steps:
      - name: Show variables
        run: |
          echo ${{ vars.ANSIBLE_CONTROLLER_URL }}, ${{ secrets.ANSIBLE_TOKEN }}
          exit 0
      - name: Send REST to Automation Gateway
        run: |
          # From variables comes
          # ANSIBLE_CONTROLLER_URL
          # From secrets comes
          # ANSIBLE_TOKEN

          
          # Choose  invnetory id depending on current branch
          BRANCH_NAME="${{ github.ref_name }}"
          if [ "$BRANCH_NAME" == "master" ]; then
            INVENTORY_ID="2"
          elif [ "$BRANCH_NAME" == "test" ]; then
            INVENTORY_ID="3"
          else
            # Set a default ID or fail the workflow for unknown branches
            echo "::error::Branch '$BRANCH_NAME' is not mapped to an inventory ID."
            exit 1
          fi
          # Start a new job through the Automation Controller API
          RESPONSE=$(curl -v -X POST -s -k \
                     -H "Content-Type: application/json" \
                     -H "Authorization: Bearer ${{ secrets.ANSIBLE_TOKEN }}" \
                     -A "nonstandardUA" \
                     --data "{\"inventory\": $INVENTORY_ID, \"extra_vars\": {\"git_branch\": \"$BRANCH_NAME\"}}"\
                     "${{ vars.ANSIBLE_CONTROLLER_URL }}/api/controller/v2/job_templates/Deploy%20Javascript%20TODO%20List%20Application/launch" \
                    ) 
          # Debug full response
          echo $RESPONSE
          # Parse to get what job was started
          JOB_ID=$(echo $RESPONSE | jq -r '.job')
          echo El job id es $JOB_ID
          
          # Pass variables to next step
          echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV

      - name: Wait for completion of deploy job
        run: |
          # Print where to find the logs
          echo Examine job progress at "${{ vars.ANSIBLE_CONTROLLER_URL }}/#/jobs/playbook/${JOB_ID}"
          
          # Query the job API to see if it has finished
          JOB_STATUS="new"
          while [[ "$JOB_STATUS" == "new" || "$JOB_STATUS" == "pending" || "$JOB_STATUS" == "running"  || "$JOB_STATUS" == "waiting" ]]; do
            sleep 10  # Poll every 30 seconds; adjust as necessary
            RESPONSE=$(curl -s -k -A "nonstandardUA" -X GET "${{ vars.ANSIBLE_CONTROLLER_URL }}/api/controller/v2/jobs/$JOB_ID/" -H "Authorization: Bearer ${{ secrets.ANSIBLE_TOKEN }}")
            JOB_STATUS=$(echo $RESPONSE | jq -r '.status')
            echo "Job status: $JOB_STATUS"
          done

          if [[ "$JOB_STATUS" == "successful" ]]; then
            echo "Job completed successfully."
            exit 0
          else
            # Handle the job failure case, print what jobs have failed
            echo "Job failed with status $JOB_STATUS."

      #       # Report failed hosts
      #       # Get job stdout to get the summary part
      #       RESPONSE=$(curl -s -k -A "nonstandardUA" -X GET "${{ vars.ANSIBLE_CONTROLLER_URL }}/api/controller/v2/jobs/$JOB_ID/stdout/?format=txt" -H "Authorization: Bearer ${{ secrets.ANSIBLE_TOKEN }}")

      #       # Print host summary from STDOUT
      #       echo "Please examine failed hosts manually:"
      #       echo "$RESPONSE" | awk '/PLAY RECAP/{flag=1} flag' | grep -E '(failed=[1-9])|(unreachable=[1-9])'
      #       echo "====================================="
      #       exit 1
          fi
